server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/mukando_auth
    username: root
    password: sudo0047
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: caffeine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: MrDCKQyMSWR8Di/nYRXZPBLR+HCbCv+KvSCDu47px80=
  expiration: 86400000         # 1 day
  refreshExpirationMs: 604800000 # 7 days
