server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-user-service
          uri: lb://auth-user-service
          predicates:
            - Path=/auth/**, /users/**
        - id: group-service
          uri: lb://group-service
          predicates:
            - Path=/api/groups/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
        - id: contribution-service
          uri: lb://contribution-service
          predicates:
            - Path=/api/contributions/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: MrDCKQyMSWR8Di/nYRXZPBLR+HCbCv+KvSCDu47px80=
  expiration: 86400000 # 1 day in ms
