server:
  port: 8761

spring:
  cloud:
    inetutils:
      prefer-ip-address: true
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    